workspace = { members = ["enough_is_enough"] }
[package]
name = "is_perfect_square"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
